plugins {
    alias(libs.plugins.android.application)
}

def keystoreProps = new Properties()
def keystoreFile = rootProject.file('keystore/keystore.properties')
if (keystoreFile.exists()) {
    keystoreProps.load(new FileInputStream(keystoreFile))
}

android {
    namespace 'me.blacknaut.greenlabs'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "me.blacknaut.greenlabs"
        minSdk 24
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            if (keystoreFile.exists()) {
                storeFile rootProject.file("keystore/${keystoreProps.getProperty('storeFile')}")
                storePassword keystoreProps.getProperty('storePassword')
                keyAlias keystoreProps.getProperty('keyAlias')
                keyPassword keystoreProps.getProperty('keyPassword')
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            if (keystoreFile.exists()) {
                signingConfig signingConfigs.release
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/*.md', 'META-INF/LICENSE*', 'META-INF/NOTICE*']
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}
